#!/usr/bin/python
import sys
import lib.edit as edit
import lib.act as act

# looks for all established connections on a given port and kills the processes
# first argument must be the portnumber



# get process numbers of processes with established connections on this port:
processlist = act.established_by_port(sys.argv[1])
#print processlist

# cut out the process numbers:
processnumbers = edit.cut_bytes(processlist,9,13)

# kill all these processes:
print "killing: %s ..." % processnumbers
processes_left=act.kill(processnumbers)
print "... assumed done." # some hung processes would need -9 or sudo, todo
 
